services:
  web:
    build: 
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    volumes:
      - type: bind
        source: /home/cqctxs/key.json
        target: /app/key.json