services:
  web:
    build: 
      context: ./website
      dockerfile: ./website/Dockerfile
    ports:
      - "8000:3000"
    
  server:
    build: 
      context: ./server
      dockerfile: ./server/Dockerfile
    ports:
      - "8001:3000"